services:
  portfolio:
    image: ${REGISTRY}/${IMAGE_NAME}:latest
    container_name: ${CONTAINER_NAME_APP}
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      # Environment
      NEXT_PUBLIC_NODE_ENV: production
      
      # Email configuration (server only)
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_USER_NO_REPLY: ${SMTP_USER_NO_REPLY}
      EMAIL_CONTACT: ${EMAIL_CONTACT}
      PHONE_NUMBER: ${PHONE_NUMBER}
      
      # Site Configuration
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
      
      # Creator Info
      NEXT_PUBLIC_CREATOR_NAME: ${NEXT_PUBLIC_CREATOR_NAME}
      NEXT_PUBLIC_CREATOR_ROLE: ${NEXT_PUBLIC_CREATOR_ROLE}
      
      # Contact Info
      NEXT_PUBLIC_EMAIL_CONTACT: ${NEXT_PUBLIC_EMAIL_CONTACT}
      NEXT_PUBLIC_PHONE_NUMBER: ${NEXT_PUBLIC_PHONE_NUMBER}
     
      # Map Coordinates
      NEXT_PUBLIC_MAP_COORDINATES: ${NEXT_PUBLIC_MAP_COORDINATES}
      
      # GitHub Configuration (server only)
      ACCESS_TOKEN_GITHUB: ${ACCESS_TOKEN_GITHUB}

      # GitHub Configuration (client only)
      NEXT_PUBLIC_GITHUB_API_URL: ${NEXT_PUBLIC_GITHUB_API_URL}
      NEXT_PUBLIC_GITHUB_USERNAME: ${NEXT_PUBLIC_GITHUB_USERNAME}
      
      # Social Media URLs
      NEXT_PUBLIC_GITHUB_URL: ${NEXT_PUBLIC_GITHUB_URL}
      NEXT_PUBLIC_LINKEDIN_URL: ${NEXT_PUBLIC_LINKEDIN_URL}

      # Firebase Configuration
      NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${NEXT_PUBLIC_FIREBASE_APP_ID}
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`elvisea.dev`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsEncrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3003"

    networks:
      - web

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3003/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

    deploy:
      update_config:
        order: start-first
        failure_action: rollback

networks:
  web:
    external: true
